name: variables and secrets
env:
  WF_VAR: "WorkFlow level variable"

on:
  push:

jobs:
  test_expressions:
    name: job to test expressions
    runs-on: ubuntu-latest
    env:
      aBoolean: ${{ true }}
      afBoolean: ${{ false }}
      aNull: ${{ null }}
      aNumber: ${{ 42 }}
      aString: this is a string
    steps:
      - name: testvars
        run: echo ${{ fromJSON(env.aBoolean) }}
      - name: check var type
        shell: python
        env:
          aBooleanz: ${{ fromJSON(env.aBoolean) }}
        run: |
          import os
          var = os.getenv("aBooleanz")
          print(type(var))
      - if: (env.aBoolean == 'true')
        run: echo wtf
      - if: ${{ env.aBoolean == 'true'}}
        run: echo finally!
      - if: ${{ env.aBoolean }}
        run: echo either the var is true or it is just set...
      - if: ${{ env.afBoolean }}
        run: echo boolean is false yet still ran...
      
      
  test_variables:
    if: (github.event_name == 'pull_request')
    name: job to test variables
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "Job level variable"
    steps:
      - name: test variables
        id: stepVar
        env:
          STEP_VAR: "Step level variable"
        run: |
          echo ${{ github.actor }}
          echo $GITHUB_JOB
          echo $WF_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo ${{ vars.CONF_VAR }}
          echo ${{ secrets.A_SECRET }}
