name: variables and secrets
env:
  WF_VAR: "WorkFlow level variable"

on:
  push:

jobs:
  test_expressions:
    name: job to test expressions
    runs-on: ubuntu-latest
    env:
      aBoolean: ${{ false }}
      afBoolean: ${{ false }}
      aNull: ${{ null }}
      aNumber: ${{ 42 }}
      aString: this is a string
    steps:
      - name: test null
        if: (env.aNull == null)
        run: echo this variable is null
      - name: test boolean
        if: ${{ fromJSON(env.aBoolean) }}
        run: echo this job wont run as our variable is false
      - name: contains function
        if: ${{ contains(env.aString, 'this') }}
        run: |
          echo "our string var contains the word 'string'"
          echos "but here is a typo to make the job fail"
      - name: always status check
        if: ${{ always() }}
        env:
          FORMAT_VAR: ${{ format('GitHub {0} {1} {2}', 'actions', 'is', 'awesome') }}
        run: |
          echo "this job ran thanks to the status check" 
          echo ${{ env.FORMAT_VAR }}
      - name: starts with function
        if: ${{ startsWith(env.aString, 'devops') }}
        run: echo "this job will be skipped"
     

    # aqui el always



    #  - name: test number
    #    if: (env.aNumber > 1)
     #   run: echo the value of aNumber is larger than 1
     # - name: test contains function
     #   if: ${{ contains(aString, 'is') } 
     #   run: echo "the variabe aString contains 'is'"



      #- name: testvars
      #  run: echo ${{ fromJSON(env.aBoolean) }}
     # - name: check var type
      #  shell: python
    #    env:
      #    aBooleanz: ${{ fromJSON(env.aBoolean) }}
     #   run: |
      #    import os
     #     var = os.getenv("aBooleanz")
      #    print(type(var))
    #  - if: (env.aBoolean == 'true')
     #   run: echo wtf
     # - if: ${{ env.aBoolean == 'true'}}
    #    run: echo finally!
      #- if: ${{ fromJSON(env.aBoolean) }}
   #     run: echo either the var is true or it is just set...

      
      
  test_variables:
    if: (github.event_name == 'pull_request')
    name: job to test variables
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "Job level variable"
    steps:
      - name: test variables
        id: stepVar
        env:
          STEP_VAR: "Step level variable"
        run: |
          echo ${{ github.actor }}
          echo $GITHUB_JOB
          echo $WF_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo ${{ vars.CONF_VAR }}
          echo ${{ secrets.A_SECRET }}
