name: variables and secrets
env:
  WF_VAR: "WorkFlow level variable"

on:
  push:

jobs:
  test_expressions:
    name: job to test expressions
    runs-on: ubuntu-latest
    env:
      aBoolean: ${{ true }}
      aNull: ${{ null }}
      aNumber: ${{ 42 }}
      aString: this is a string
    steps:
      - name: testvars
        run: echo env.aBoolean
      - if: (env.aBoolean == true)
        run: echo wtf
      
      
  test_variables:
    if: (github.event_name == 'pull_request')
    name: job to test variables
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "Job level variable"
    steps:
      - name: test variables
        id: stepVar
        env:
          STEP_VAR: "Step level variable"
        run: |
          echo ${{ github.actor }}
          echo $GITHUB_JOB
          echo $WF_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo ${{ vars.CONF_VAR }}
          echo ${{ secrets.A_SECRET }}
